name: Test React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test app
        run: npm run test
